type Word {
  id: ID!
  word: String!
  translations: [Translation!]!
}

type Translation {
  id: ID!
  translation: String!
  exampleSentences: [ExampleSentence!]!
}

type ExampleSentence {
  id: ID!
  sentence: String!
}

input FullRecordInput {
  word: String!
  translation: String!
  examples: [String!]
}

type Query {
  getWordTranslation(word: String!): Word
}

type Mutation {
  createTranslation(input: FullRecordInput!): Boolean!
  addTranslation(input: FullRecordInput!): Boolean!
  addExample(input: FullRecordInput!): Boolean!
  deleteWord(word: String!): Boolean!
  deleteTranslation(word: String!, translation: String!): Boolean!
  deleteExample(input: FullRecordInput!): Boolean!
}
