FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /dictionary-client ./client

FROM alpine:latest

WORKDIR /

COPY --from=builder /dictionary-client /dictionary-client

ENTRYPOINT ["/dictionary-client"]