FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY server/ ./server/

RUN CGO_ENABLED=0 GOOS=linux go build -o /dictionary-server ./server

FROM alpine:latest

WORKDIR /

COPY --from=builder /dictionary-server /dictionary-server

EXPOSE 8080

CMD ["/dictionary-server"]