package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"log"

	"github.com/annap16/DictionaryApp/graph/model"
)

// CreateTranslation is the resolver for the createTranslation field.
func (r *mutationResolver) CreateTranslation(ctx context.Context, input model.CreateTranslationInput) (bool, error) {
	err := r.DBInterface.AddWord(input)
	if err != nil {
		log.Fatal("Create Word error")
		return false, err
	}
	return true, nil
}

// DeleteWord is the resolver for the deleteWord field.
func (r *mutationResolver) DeleteWord(ctx context.Context, word string) (bool, error) {
	return r.DBInterface.DeleteWord(word)
}

// GetWordTranslation is the resolver for the getWordTranslation field.
func (r *queryResolver) GetWordTranslation(ctx context.Context, word string) (*model.Word, error) {
	return r.DBInterface.ReceiveWordTranslation(word)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
