type Word {
  id: ID!
  word: String!
  translations: [Translation!]!
}

type Translation {
  id: ID!
  translation: String!
  exampleSentences: [ExampleSentence!]!
}

type ExampleSentence {
  id: ID!
  sentence: String!
}

input CreateTranslationInput {
  word: String!
  translation: String!
  examples: [String!]
}

type Query {
  getWordTranslation(word: String!): Word
}

type Mutation {
  createTranslation(input: CreateTranslationInput!): Boolean!
  addTranslation(input: CreateTranslationInput!): Boolean!
  addExample(translation: String!, examples: [String!]): Boolean!
  deleteWord(word: String!): Boolean!
  deleteTranslation(translation: String!): Boolean!
  deleteExample(example: String!): Boolean!
}
