package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"

	"github.com/annap16/DictionaryApp/graph/model"
)

// CreateTranslation is the resolver for the createTranslation field.
func (r *mutationResolver) CreateTranslation(ctx context.Context, input model.CreateTranslationInput) (*model.Word, error) {
	// Example return without DB integration
	word := &model.Word{
		ID:   "123",
		Word: input.Word,
		Translations: []*model.Translation{
			{
				ID:          "1",
				Translation: input.Translation,
				ExampleSentences: func() []*model.ExampleSentence {
					var exampleSentences []*model.ExampleSentence
					for i, sentence := range input.Examples {
						exampleSentences = append(exampleSentences, &model.ExampleSentence{
							ID:       fmt.Sprintf("%d", i+1),
							Sentence: sentence,
						})
					}
					return exampleSentences
				}(),
			},
		},
	}

	return word, nil
}

// GetWordTranslation is the resolver for the getWordTranslation field.
func (r *queryResolver) GetWordTranslation(ctx context.Context, word string) (*model.Word, error) {
	// Example return without DB integration
	return &model.Word{
		ID:   "123",
		Word: word,
		Translations: []*model.Translation{
			{
				ID:          "1",
				Translation: "house",
				ExampleSentences: []*model.ExampleSentence{
					{ID: "1", Sentence: "Dr House"},
				},
			},
		},
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
