// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ExampleSentence struct {
	ID       string `json:"id"`
	Sentence string `json:"sentence"`
}

type FullRecordInput struct {
	Word        string   `json:"word"`
	Translation string   `json:"translation"`
	Examples    []string `json:"examples,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Translation struct {
	ID               string             `json:"id"`
	Translation      string             `json:"translation"`
	ExampleSentences []*ExampleSentence `json:"exampleSentences"`
}

type Word struct {
	ID           string         `json:"id"`
	Word         string         `json:"word"`
	Translations []*Translation `json:"translations"`
}
